### ISSUE TITLE
[Bug] AttributeError: type object 'spmatrix' has no attribute 'div'.

### ISSUE THREAD

**Issue by yogiyadav08** [OpenBB-finance/OpenBBTerminal#5208]
### AttributeError: type object 'spmatrix' has no attribute '__div__'. Did you mean: '__dir__'?
getting below error while importing openbb

>>> from openbb_terminal.sdk import openbb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/openbb_terminal/sdk.py", line 43, in <module>
    import openbb_terminal.core.sdk.sdk_init as lib
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/openbb_terminal/core/sdk/sdk_init.py", line 642, in <module>
    from openbb_terminal.portfolio.portfolio_optimization import (
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/openbb_terminal/portfolio/portfolio_optimization/optimizer_model.py", line 13, in <module>
    import riskfolio as rp
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/riskfolio/__init__.py", line 9, in <module>
    from .Portfolio import *
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/riskfolio/Portfolio.py", line 11, in <module>
    import cvxpy as cv
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/cvxpy/__init__.py", line 18, in <module>
    import cvxpy.interface.scipy_wrapper
  File "/Users/anaconda3/envs/obb/lib/python3.10/site-packages/cvxpy/interface/scipy_wrapper.py", line 37, in <module>
    method = getattr(spmatrix, method_name)
AttributeError: type object 'spmatrix' has no attribute '__div__'. Did you mean: '__dir__'?

**Comment by jmaslek** [comment]
As far as I know, this should be resolved now.  I just successfully installed the openbb-nightly build and this issue no longer appears

**Comment by deeleeramone** [comment]
Just did a fresh install from `openbb-nightly[all]` on Windows 11 Pro, everything went well and the SDK initialized as expected.

**Comment by jmaslek** [comment]
I believe this issue has been resolved as of the latest release.

**Comment by sammybaddazz** [comment]
This issue is not resolved yet. I just received this same error.

**Comment by sammybaddazz** [comment]
Running conda install -c conda-forge scikit-learn=1.2.1 scipy=1.10.1 solved the issue, however running pip install openbb-nightly[all] did not resolve the issue.

**Comment by deeleeramone** [comment]
It sounds like you just reinstalled the problematic versions after fixing it. Erase the environment entirely, clear your cache and create a new one.

**Comment by deeleeramone** [comment]
> I updated my packages on Windows 11 via conda and got this error. I then removed the environment. Created a new environment follow the steps on the OpenBB site. I still get this ERROR: 37 method = getattr(spmatrix, method_name) 38 new_method = wrap_bin_op(method) 39 setattr(spmatrix, method_name, new_method)
> 
> AttributeError: type object 'spmatrix' has no attribute '**div**'
> 
> Next: I ran "pip install openbb-nightly[all] " and then restarted the kernel and I still got this error. All was working OK before the step mentioned above. There are too many important programs I need to run now. I will be looking for a replacement for OpenBB while I wait for a possible fix.

This is almost certainly related to installing packages in an order that creates conflicts and do not conform to the Poetry `.lock` file.

Similar errors have occurred where a bad version of `numexpr` is installed, which breaks Pandas.

https://github.com/pydata/numexpr/issues/444

**Comment by jmmelen** [comment]
I had tried to take care of conflicts by uninstalling packages and reinstalling them and I still got the "spmatrix" error.
Looking over problems is "tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2," however, "OpenBB requires protobuf 3.20.1"
Please read my updated origin comment where I tried to fix the problem. 
If my problem is order-related, my original install just followed the steps on the OpenBB site  and had problems.  
If you think it's order install related please supply your steps for install.

**Comment by deeleeramone** [comment]
> I had tried to take care of conflicts by uninstalling packages and reinstalling them and I still got the "spmatrix" error. Looking over problems is "tensorboard 2.10.1 requires protobuf<3.20,>=3.9.2," however, "OpenBB requires protobuf 3.20.1" 

These messages from `pip` are simply warnings. They do not stop you from using them.  

The `requirements-full.txt` file lists the version of tensorboard as a higher version than your error:

```
tensorboard==2.13.0 ; python_full_version >= "3.8.1" and python_full_version != "3.9.7" and python_version < "3.11"
```

You may also need to purge your cache.

**Comment by jmmelen** [comment]
Read my comment carefully.  Again, I had made the new environment and followed the installation directions on the OpenBB site.  This gave ERRORS when running code that was working last week.  The TensorFlow was added after. OK.

**Comment by deeleeramone** [comment]
> The TensorFlow was added after. OK

This is almost certainly the issue. You are installing different versions of an unknown number of packages, apparently downgrading some because how else would you end up with versions that are lower than the OpenBB requirements file?

**Comment by jmmelen** [comment]
Read the full comments.  
1) I got errors running code after following the steps for installation on the OpenBB site.
2) Then I installed TensorFlow.  That is where I got the "spmatrix" error. 
3) Try to read all the comments. 
4) Other errors were introduced with fixes that make sense.  
5) Since I keep saying I started with creating a new Environment, there wouldn't be an issue relating to "clearing cache."

**Comment by deeleeramone** [comment]
> Read the full comments.
> 
>     1. I got errors running code after following the steps for installation on the OpenBB site.

The only error you have mentioned is `spmatrix`. 

>     2. Then I installed TensorFlow.  That is where I got the "spmatrix" error.


When you install from `pip` it checks the cache first, and that is shared between environments.

>     5. Since I keep saying I started with creating a new Environment, there wouldn't be an issue relating to "clearing cache."

**Comment by jmmelen** [comment]
1) No. Again read, I said with the install of a NEW ENVIRONMENT, I got errors.  I didn't both namely all of them.
2) I was the one who said installing TensorFlow gave the "spmatrix" error. So, when you say "Clearly TensorFlow is the problem..." You are so certain of what I had in my comments.

**Comment by jmmelen** [comment]
No Cache Issue.  The cache is for "sharing packages." There are no problems created by the cache.  If I listened to you, removing cache would have created all over my environments

**Comment by jmmelen** [comment]
I got it working. 
1) I followed some of my previous steps.  
2) Ran some code that worked. 
3) Other code in Python required installing more packages.  
4) I'm "handcuffed" now with code.  Previous working code that used OpenBB to extract data and then fed the data into a code for making predictions  -- better models than those simple ones in OpenBB -- no longer works.  I have to save the data, and then read it into another program that is in another environment.  
Great with your OpenBB updates! (Things working last week don't work!) Ha!!

**Comment by deeleeramone** [comment]
> 1. No. Again read, I said with the install of a NEW ENVIRONMENT, I got errors.  I didn't both namely all of them.

OK, "I get errors" is not helpful. If you don't say what it is, there's nothing anyone can do to help and it can only be described as user-error.

What is the version of `numexpr` that you have installed?

Environment management is not OpenBB's responsibility, Python packages and extensions can and will alter them where valid syntax is no longer valid.
